<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  
  <!--
  <ItemGroup>
    <Reference Include="ModelMediator.Abstractions">
      <HintPath>/home/sable/MonoGame/Codegen/ModelMediator/ModelMediator.Abstractions/bin/Debug/net10.0/ModelMediator.Abstractions.dll</HintPath>
    </Reference>
    <Analyzer Include="/home/sable/MonoGame/Codegen/ModelMediator/ModelMediator/bin/Debug/netstandard2.0/ModelMediator.dll" />
    <Analyzer Include="/home/sable/MonoGame/Codegen/ModelMediator/ModelMediator/bin/Debug/netstandard2.0/Scriban.Signed.dll" />
  </ItemGroup>  
  -->
  <ItemGroup>
    <ProjectReference Include="../SolsDawn.Core/SolsDawn.Core.csproj" />
  </ItemGroup> 
  
  <ItemGroup>
    <PackageReference Include="Aether.Physics2D.MG" Version="2.2.0" />
    <PackageReference Include="Gum.MonoGame" Version="2026.5.8.1" />
    <PackageReference Include="MonoGame.Extended" Version="6.0.0" />
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5-preview.4">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="ObservableCollections.R3" Version="3.3.4" />
    <PackageReference Include="Stateless" Version="5.20.1" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="Configs\Lua\**\*.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>