<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="../SolsDawn.Core/SolsDawn.Core.csproj" />
  </ItemGroup> 
  
  <ItemGroup>
    <PackageReference Include="Aether.Physics2D.MG" Version="2.2.0" />
    <PackageReference Include="Apos.Shapes" Version="0.8.1" />
    <PackageReference Include="Gum.MonoGame" Version="2026.5.8.1" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="MonoGame.Extended" Version="6.0.0" />
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>