<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../SolsDawn.Core/Assets/Icon.ico</ApplicationIcon>
    <AssemblyName>SolsDawn</AssemblyName>
    <MonoGamePlatform>DesktopGL</MonoGamePlatform>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SolsDawn.Core.Logic/SolsDawn.Core.Logic.csproj" />
    <ProjectReference Include="../SolsDawn.Gameplay/SolsDawn.Gameplay.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5" />
  </ItemGroup>
  <Import Project="..\SolsDawn.Content\BuildContent.targets" />
</Project>